### ISSUE TITLE
npm run dev - throws an exception

### ISSUE THREAD

**Issue by SangameshPH** [yannickglt/angular-webpack-boilerplate#1]
Hello @yannickglt ,
It is nice boiler plate for Angular1.x and webpack. I am trying to run this in my local. But seem like it npm run dev throws an exception.

> angular-webpack-workflow@1.0.0 dev D:\Erlangen_MichaelLaptop\TryOuts\webpack\angular-webpack-boilerplate-master
> webpack-dev-server --history-api-fallback --inline --progress

 30% 1/3 build modulesevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-webpack-workflow@1.0.0 dev: `webpack-dev-server --history-api-fallback --inline --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-webpack-workflow@1.0.0 dev script 'webpack-dev-server --history-api-fallback --inline --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-webpack-workflow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --history-api-fallback --inline --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-webpack-workflow
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-webpack-workflow
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Erlangen_MichaelLaptop\TryOuts\webpack\angular-webpack-boilerplate-master\npm-debug.log

Do you know how to solve this?

Thank you,

**Comment by SangameshPH** [comment]
I am sorry, it was my mistake. I was already running webpack in another window. But its good to know. :)

**Comment by yannickglt** [comment]
Glad to hear it helps you 😉
